Repository GardenOfWriter/garden-of-writer-server, pull requests merged in 2024-01, with the labels that each got.

#34 #18 카테고리 enum타입으로 분리
  src/novel-room/entities/enum/novel-room-category.enum.ts
  src/novel-room/entities/novel-room.entity.ts
Labels: feat

#35 #18 카테고리 관련 타입 수정
  src/novel-attend-board/dto/response/findall.dto.ts
  src/novel-room/dto/create-novel-room.dto.ts
  src/novel-room/dto/response/find-attend-status.dto.ts
  src/novel-room/dto/update-novel-room.dto.ts
  src/novel-room/entities/novel-room.entity.ts
  src/novel-room/novel-room.service.ts
Labels: fix

#44 #18 casl 적용 및 스웨거 문서 설명 추가
  src/app.module.ts
  src/auth/guard/casl.guard.ts
  src/commons/abilities/ability.factory.ts
  src/commons/abilities/ability.module.ts
  src/commons/abilities/action.factory.ts
  src/commons/decorator/casl.decorator.ts
  src/novel-room/novel-room.controller.ts
  src/novel-room/novel-room.module.ts
  src/novel-room/novel-room.service.ts
  src/user/user.controller.ts
Labels: feat

#45 #18 exception 수정
  src/novel-room/novel-room.service.ts
Labels: refactor

#46 Bug/dependency action factory
  src/novel-room/novel-room.module.ts
Labels: fix

#48 Refactor/47 alias setting
  package.json
  src/chapter/entities/chapter-comment.entity.ts
  src/chapter/entities/chapter.entity.ts
  src/commons/abilities/ability.factory.ts
  src/novel-attend-board/dto/response/findall.dto.ts
  src/novel-room/dto/create-novel-room.dto.ts
  src/novel-room/dto/response/find-attend-status.dto.ts
  src/novel-room/dto/update-novel-room.dto.ts
  src/novel-room/entities/novel-room.entity.ts
  src/novel-writer/entities/novel-writer.entity.ts
  src/novel-writer/repository/novel-writer.repository.impl.ts
  tsconfig.json
Labels: refactor
